name: ost

on:
  issue_comment:
    types: [created]

jobs:
  call-ost-trigger:
# if: ${{ github.event.issue.pull_request && github.event.review.state == 'approved' && github.event.comment.body == '/ost'}}
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/ost'}}
    uses: oVirt/test-ost/.github/workflows/ost-trigger.yaml@main
    with:
      url: ${{ github.event.issue.pull_request.url }}
    secrets:
      OST_LISTEN_PORT: ${{ secrets.OST_LISTEN_PORT }}

  triggered:
    needs: call-ost-trigger
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge command
        uses: actions/github-script@v5
        with:
          script: |
            github.reactions.createForIssueComment({
              comment_id: context.payload.comment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: 'rocket',
            });

  log:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/ost'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: console.log(context)
