name: ost

on:
  issue_comment:
    types: [created]

  workflow_dispatch:
    inputs:
      pr_url:
        required: true
        type: string

jobs:
  trigger-ost:
# if: ${{ github.event.issue.pull_request && github.event.review.state == 'approved' && github.event.comment.body == '/ost'}}
    if: ${{ (github.event.issue.pull_request && github.event.comment.body == '/ost') || github.event.inputs.pr_url }}
    runs-on: self-hosted
    timeout-minutes: 4
    steps:
      - name: trigger
        env:
          SHA: "${{ github.event.issue.pull_request.head.sha }}"
          CHECK_SUITES: "${{ github.event.issue.pull_request.base.repo.url }}/commits/${{ github.event.issue.pull_request.head.sha }}/check-suites"
          PR_URL: "${{ github.event.issue.pull_request.url }}${{ github.event.inputs.pr_url }}"
        run: |
          cd /var/lib/nginx/gh
          [[ -z "$SHA" ]] && { SHA=$(curl -sS ${PR_URL} | jq -r .head.sha); CHECK_SUITES="$(curl -sS ${PR_URL} | jq -r .base.repo.url)/commits/${SHA}/check-suites"; }
          BASE_TIME=$(curl -sS ${CHECK_SUITES} | jq -r ".check_suites[] | select(.app.id==164117) | select(.head_commit.id==\"${SHA}\") | .updated_at")
          echo ${{inputs.pr_url }}${{ github.event.issue.pull_request.url }} | runuser -u nginx tee queue
          i=0
          while [ $i -lt 12 ]; do
            sleep 10
            UPDATE_TIME=$(curl -sS ${CHECK_SUITES} | jq ".check_suites[] | select(.app.id==164117) | select(.head_commit.id==\"${SHA}\") | .updated_at")
            echo -n "try $((i++)): $UPDATE_TIME"
            [[ "$BASE_TIME" != "$UPDATE_TIME" ]] && break
          done
          rm -f queue
          [[ "$BASE_TIME" != "$UPDATE_TIME" ]]
